apiVersion: v1
kind: Pod
metadata:
  name: api
spec:
  containers:
    - image: gopen-api:latest
      imagePullPolicy: IfNotPresent
      name: api
      livenessProbe:
          httpGet:
            path: health
            port: 3000
          initialDelaySeconds: 2
          failureThreshold: 1
          successThreshold: 1
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP