apiVersion: v1
kind: Service
metadata:
  labels:
    app: gopen
  name: gopen-api
spec:
  ports:
    - nodePort: 30000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: gopen-api
  type: NodePort
